import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "../globals.css";
import DashboardNav from "@/components/shared/DashboardNav";
import MobileTabs from "@/components/shared/MobileTabs";

const inter = Poppins({ weight: ["300", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardNav />
        <AntdRegistry>{children}</AntdRegistry>
        <MobileTabs />
      </body>
    </html>
  );
}
